apiVersion: v1
kind: Service
metadata:
  name: scdf-gateway
  labels:
    app: scdf-gateway
    component: scdf-gateway
    type: scdf-gateway
    spring-deployment-id: scdf-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      name: scdf-gateway
      targetPort: 9090
      protocol: TCP
  selector:
    app: scdf-gateway
    component: scdf-gateway