apiVersion: v1
kind: Service
metadata:
  name: scdf-rest-facade
  labels:
    app: scdf-rest-facade
    component: scdf-rest-facade
    type: scdf-facade
    spring-deployment-id: scdf-rest-facade
spec:
  type: NodePort
  ports:
    - port: 80
      name: scdf-facade-port
      targetPort: 8080
      protocol: TCP
  selector:
    app: scdf-rest-facade
    component: scdf-rest-facade